# Generated by Django 3.2.6 on 2022-05-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_comment_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
