# Generated by Django 3.2.6 on 2022-05-24 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0009_auto_20220524_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedmovielist',
            name='movie',
            field=models.ManyToManyField(null=True, related_name='user_liked_movies', to='movie.Movie'),
        ),
        migrations.AlterField(
            model_name='likedmovielist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_like_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
