# Generated by Django 3.2.6 on 2022-05-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_likedmovielist_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedmovielist',
            name='movie',
            field=models.ManyToManyField(blank=True, to='movie.Movie'),
        ),
    ]
